### PR TITLE
Snowball as module

### PR DESCRIPTION
**Pull request by danielSanchezQ**
* Created snowball tiny module
* Moved initial gist to package

### CODE REVIEW

**Comment by jessiebroke** [comment]
Nice refactoring and turning it into a module.

**Comment by jessiebroke** [comment]
Would you like me to Squash and merge?

**Comment by arnetheduck** [comment]
where are we on renaming glacier btw?

**Comment by jessiebroke** [comment]
> where are we on renaming glacier btw?

When we get past the quack in consensus.

**Comment by danielSanchezQ** [comment]
> Would you like me to Squash and merge?

@jessiebroke yeah, but usually If you are a reviewer, you just need to approve it. Then I can merge it myself too 😄

**Review by jessiebroke — APPROVED** [review]
Looks good.

**Pull request merged**
